# The front repo is prior if conflicted
# CocoaPods private repo
source 'https://github.com/jcccn/PodSpecs.git'
# CocoaPods master repo
source 'https://github.com/CocoaPods/Specs.git'

platform :ios,'6.1'

# ignore all warnings from all pods
inhibit_all_warnings!

pod 'BlocksKit'

pod 'MBProgressHUD'

pod 'Appirater'

pod 'RETableViewManager'

pod 'RESideMenu'

pod 'Masonry'

pod 'TPKeyboardAvoiding'

pod 'UMAnalytics'

pod 'UMFeedback'

pod 'ShareSDK/Normal'
