source 'https://github.com/CocoaPods/Specs.git'

platform :ios,'6.1'

# ignore all warnings from all pods
inhibit_all_warnings!

pod 'BlocksKit'

pod 'MBProgressHUD'

pod 'Appirater'

pod 'RETableViewManager'

pod 'RESideMenu'

pod 'Masonry'

pod 'UMengAnalytics-NO-IDFA'

pod 'UMFeedback', :git => 'https://github.com/jcccn/UMeng-Feedback-iOS.git'

pod 'ShareSDK/Normal', :git => 'https://github.com/jcccn/ShareSDK-iOS.git'
